### PR TITLE
0.0.3 stable

### PR DESCRIPTION
**Pull request by danmunn**
Updated stable thanks to issue found by archonwang. (Misplaced file). Also noticed that utilising script/css includes in lib wasn't too effective, css include now part of view, JS added to header.

### CODE REVIEW

**Comment by tastapod** [comment]
This is great, thanks. The original plugin doesn't have any tests, but have you run this against the latest Chiliproject or Redmine test suites to see if it all still hangs together?

**Comment by danmunn** [comment]
Not tested against Chiliproject, will do test shortly and update.

**Comment by tastapod** [comment]
Thanks Daniel, that's great. Does that close out both the open issues?

On 24 May 2012 15:05, Daniel Munn <
reply@reply.github.com

**Comment by danmunn** [comment]
Hi Dan, there is an incompatibility between rendering rendering approach between Redmine and Chiliproject - that being said it's about a 2 minute fix (however both would not be compatible with the other). This was just a work-up on the existing plugin, and it does fix the other outstanding issues - if you want I can create an additional branch for chiliproject?

**Comment by tastapod** [comment]
I suggest we go with this version and if someone wants to create
chiliproject_issue_history_tabs as a fork or a branch they'll have a good
place to start :)
On May 24, 2012 5:19 PM, "Daniel Munn" <
reply@reply.github.com>
wrote:

**Comment by danmunn** [comment]
Agree, have branched it regardless for Chiliproject and seems to work, although not done any extensive testing on it - would suggest someone forking for ongoing maintenance of that :)

**Comment by tastapod** [comment]
Nice one. Push the branch up too and I'll merge that.
On May 26, 2012 4:56 AM, "Daniel Munn" <
reply@reply.github.com>
wrote:

**Comment by danmunn** [comment]
Both branches have been pushed already; 0.0.3-stable sits for redmine, other branch named ChiliProject.

**Pull request merged**
