### PR TITLE
0.0.3 stable

### PR DESCRIPTION
**Pull request by danmunn**
For your review, will resolve both outstanding issues on your queue - and can confirm this is compatible with redmine 2.0.0

### CODE REVIEW

**Comment by archonwang** [comment]
Hi, danmunn, 

I tested it on Redmine 2.0 and found it could not show any tab with plugin.

and I found nothing wrong in log error. anything I missed?

**Comment by archonwang** [comment]
Hi, damunn

I found that log donot record using the plugin page? maybe it should use the routes.rb. any idea?

<pre>
Started GET "/issues/4104" for 192.168.3.58 at Thu May 24 15:01:13 +0800 2012
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"4104"}
  Rendered issues/_action_menu.html.erb (6.6ms)
  Rendered attachments/_links.html.erb (24.4ms)
  Rendered issue_relations/_form.html.erb (1.9ms)
  Rendered issues/_relations.html.erb (3.5ms)
  Rendered issues/_history.html.erb (13.1ms)
  Rendered issues/_action_menu.html.erb (4.7ms)
  Rendered issues/_form_custom_fields.html.erb (7.1ms)
  Rendered issues/_attributes.html.erb (188.4ms)
  Rendered issues/_form.html.erb (207.1ms)
  Rendered attachments/_form.html.erb (2.2ms)
  Rendered issues/_edit.html.erb (336.1ms)
  Rendered issues/_sidebar.html.erb (12.4ms)
  Rendered watchers/_watchers.html.erb (5.4ms)
  Rendered issues/show.html.erb within layouts/base (463.7ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (1.7ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.2ms)
Completed 200 OK in 813ms (Views: 279.2ms | ActiveRecord: 458.6ms)
</pre>

**Comment by danmunn** [comment]
Hi archonwang,

Entirely my fault - I'm just re-commiting to branch, looks like in my haste of downloading from development VM I moved _history.html.erb out of its issues folder within the plugin if you move:
plugins/redmine_issues_history_tabs/app/views/_history.html.erb to
plugins/redmine_issues_history_tabs/app/views/issues/_history.html.erb
this will resolve issue - alternatively if you pull again shortly - I'll have resolved this.

**Comment by archonwang** [comment]
Nice. thanks.

**Pull request closed without merging**
